"""TrueNAS cron jobs -> /etc/cron.d/tn2fbsd.

TrueNAS stores user cron jobs in tasks_cronjob and runs them through midclt
(see etc_files/cron.d/middlewared.mako and plugins/cron.py). FreeBSD's cron(8)
reads /etc/cron.d directly, so each enabled job becomes one system crontab line
with the user-name field, matching cronjob.construct_cron_command: the five
schedule fields, the user, an inline PATH, the command, and > /dev/null /
2> /dev/null when the job hides stdout / stderr.
"""
from ..db import as_bool
from ..text import text

_CRON_PATH = "/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/root/bin"

_CRON_D_PATH = "etc/cron.d/tn2fbsd"


def generate(ctx):
    jobs = ctx.db.all("tasks_cronjob", where="cron_enabled=1", order="id")
    if not jobs:
        return

    lines = ["# Generated by tn2fbsd from TrueNAS cron jobs."]
    for job in jobs:
        parts = [
            job["cron_minute"],
            job["cron_hour"],
            job["cron_daymonth"],
            job["cron_month"],
            job["cron_dayweek"],
            job["cron_user"],
            f'PATH="{_CRON_PATH}"',
            job["cron_command"].replace("\n", ""),
        ]
        if as_bool(job["cron_stdout"]):
            parts.append("> /dev/null")
        if as_bool(job["cron_stderr"]):
            parts.append("2> /dev/null")
        lines.append(" ".join(parts))

    ctx.out.write(_CRON_D_PATH, "\n".join(lines))
    ctx.note(text("notes", "cron", path=f"/{_CRON_D_PATH}"), "cron")
