"""Assemble /etc/rc.conf.

Order (later lines override earlier ones): the verbatim base defaults asset,
the DB-derived hostname, network configuration, service enablement and service
flags, RC-type tunables, and the system_advanced settings last so they override
the static fallback. Options within each generated section are sorted
alphabetically.
"""
from .. import ASSETS_DIR
from ..db import as_bool
from . import advanced, network, nfs, ssh, tunables

NFS_ENABLE = [
    'mountd_enable="YES"',
    'nfs_server_enable="YES"',
    'rpc_lockd_enable="YES"',
    'rpc_statd_enable="YES"',
    'rpcbind_enable="YES"',
]
SMB_ENABLE = [
    'samba_server_enable="YES"',
    'smbd_enable="YES"',
    'winbindd_enable="YES"',
]


def generate(ctx):
    gc = ctx.db.one("network_globalconfiguration")
    services = {
        r["srv_service"]: as_bool(r["srv_enable"])
        for r in ctx.db.all("services_services")
    }

    parts = [(ASSETS_DIR / "rc.conf.base").read_text().rstrip("\n")]

    def section(title, lines):
        if lines:
            parts.append("")
            parts.append(f"# {title} (generated by tn2fbsd)")
            parts.extend(sorted(lines))

    section("Hostname", [f'hostname="{network.fqdn(gc)}"'])
    # Import cached pools and mount their datasets at boot (see MIGRATION.md).
    section("ZFS", ['zfs_enable="YES"'])
    section("Network", network.rcconf_lines(ctx.db))

    service_lines = []
    if services.get("nfs"):
        service_lines += NFS_ENABLE + nfs.rcconf_lines(ctx.db)
    if services.get("cifs"):
        service_lines += SMB_ENABLE
    service_lines += ssh.rcconf_lines(services.get("ssh", False))
    section("Services", service_lines)

    rc_tunables = [
        tunables.line(r["tun_var"], r["tun_value"], r["tun_comment"], quote=True)
        for r in tunables.enabled(ctx.db, "rc")
    ]
    section("Tunables (rc)", rc_tunables)

    # Kept last so real database settings override the static fallback block.
    section("System", advanced.rcconf_lines(ctx.db))

    ctx.out.write("etc/rc.conf", "\n".join(parts))
