"""SSH service -> base-system sshd: /etc/ssh/sshd_config, host keys, rc.conf.

TrueNAS runs the ports OpenSSH (rc knob openssh_enable). On a stock FreeBSD
system the base-system sshd is used: openssh_enable is set to NO and sshd_enable
to YES.

The sshd_config is built from services_ssh using directives supported by
base-system OpenSSH 9.x, mapping each TrueNAS option to its current equivalent.

Host keys are stored in the database base64-encoded, the private keys also
pwenc-encrypted (see plugins/ssh.py save_keys). They are decoded and written to
/etc/ssh so the migrated server keeps its host identity.
"""
import base64

from .. import pwenc
from ..db import as_bool, json_list, words
from ..text import text

# Host key types migrated to base-system OpenSSH 9.x.
HOST_KEY_TYPES = ["ecdsa", "ed25519", "rsa"]


def rcconf_lines(ssh_enabled):
    # The base-system sshd replaces the ports OpenSSH used by TrueNAS.
    lines = ['openssh_enable="NO"']
    if ssh_enabled:
        lines.append('sshd_enable="YES"')
    return lines


def _bind_addresses(db, cfg):
    names = words(cfg["ssh_bindiface"].replace(",", " "))
    if not names:
        return []
    interfaces = {r["int_interface"]: r for r in db.all("network_interfaces")}
    addresses = ["127.0.0.1"]
    for name in names:
        row = interfaces.get(name)
        if not row:
            continue
        if row["int_ipv4address"]:
            addresses.append(row["int_ipv4address"])
        if row["int_ipv6address"]:
            addresses.append(row["int_ipv6address"])
    return addresses


def _sshd_config(db, cfg):
    weak_ciphers = json_list(cfg["ssh_weak_ciphers"])
    log_level = cfg["ssh_sftp_log_level"] or "ERROR"
    log_facility = cfg["ssh_sftp_log_facility"] or "AUTH"

    lines = ["# Generated by tn2fbsd from the TrueNAS SSH service configuration."]
    if cfg["ssh_tcpport"] > 0:
        lines.append(f"Port {cfg['ssh_tcpport']}")
    for address in _bind_addresses(db, cfg):
        lines.append(f"ListenAddress {address}")

    lines.append("PermitRootLogin yes" if as_bool(cfg["ssh_rootlogin"])
                 else "PermitRootLogin prohibit-password")
    lines.append("PasswordAuthentication yes" if as_bool(cfg["ssh_passwordauth"])
                 else "PasswordAuthentication no")
    lines.append("PubkeyAuthentication yes")
    lines.append("KbdInteractiveAuthentication no")
    if as_bool(cfg["ssh_kerberosauth"]):
        lines.append("GSSAPIAuthentication yes")
    lines.append("AllowTcpForwarding yes" if as_bool(cfg["ssh_tcpfwd"])
                 else "AllowTcpForwarding no")
    lines.append("Compression yes" if as_bool(cfg["ssh_compression"])
                 else "Compression no")
    lines.append("UseDNS no")
    lines.append("ClientAliveInterval 15")
    lines.append("ClientAliveCountMax 3")
    lines.append("VersionAddendum none")
    if "AES128-CBC" in weak_ciphers:
        lines.append("Ciphers +aes128-cbc")
    lines.append(f"Subsystem\tsftp\t/usr/libexec/sftp-server -l {log_level} -f {log_facility}")
    if cfg["ssh_options"].strip():
        lines.append(cfg["ssh_options"].strip())
    return "\n".join(lines)


def _write_host_keys(ctx, cfg):
    written = False
    for key_type in HOST_KEY_TYPES:
        private = cfg[f"ssh_host_{key_type}_key"]
        public = cfg[f"ssh_host_{key_type}_key_pub"]
        if not private or not public:
            continue
        private_pem = base64.b64decode(pwenc.decrypt(ctx.pwenc_secret, private)).decode("utf8")
        public_key = base64.b64decode(public).decode("utf8")
        ctx.out.write(f"etc/ssh/ssh_host_{key_type}_key", private_pem, mode=0o600)
        ctx.out.write(f"etc/ssh/ssh_host_{key_type}_key.pub", public_key, mode=0o644)
        written = True
    return written


def generate(ctx):
    enabled = any(
        r["srv_service"] == "ssh" and as_bool(r["srv_enable"])
        for r in ctx.db.all("services_services")
    )
    if not enabled:
        return

    cfg = ctx.db.one("services_ssh")
    if not cfg:
        return

    ctx.out.write("etc/ssh/sshd_config", _sshd_config(ctx.db, cfg))
    if _write_host_keys(ctx, cfg):
        ctx.note(text("notes", "ssh_host_keys"), "ssh")
    _migrate_authorized_keys(ctx)
    ctx.note(text("notes", "ssh_enabled"), "ssh")


def _migrate_authorized_keys(ctx):
    # authorized_keys is not stored in the config database. Non-root users keep
    # theirs in their home directory, which comes with the ZFS pool import. root's
    # authorized_keys lives on the boot pool and is only present in the export when
    # the "Export authorized_keys for root" option was enabled.
    if ctx.root_authorized_keys:
        ctx.out.write("root/.ssh/authorized_keys", ctx.root_authorized_keys, mode=0o600)
        ctx.note(text("notes", "ssh_authorized_keys_present"), "ssh")
    else:
        ctx.note(text("notes", "ssh_authorized_keys_absent"), "ssh")
